name: aad_oauth_example_b2c
description: A Flutter OAuth package example for performing user authentication against Azure B2C OAuth2 v2.0 endpoint.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  aad_oauth:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true