name: 'Automatically stale and close issues'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-label: 'stale'
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
            If you still think this issue is needed, reopen it again.
          days-before-stale: 60
          days-before-close: 31
          exempt-issue-labels: 'pinned, security'
          close-issue-message: 'Closing this issue due to lack of activity.'
